# Generated by Django 4.2.30 on 2026-06-07 07:03

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_description_product_long_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='long_description',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
